baseURL: "https://stoplightio.github.io/docs-gen3/"
languageCode: "en-us"
title: "Stoplight Enterprise"
theme: book
publishDir: docs
disableKinds:
- taxonomy
- taxonomyTerm
BookMenuBundle: /menu
BookSection: "*"
BookEnableJS: true
